# Generated by Django 4.2.5 on 2023-09-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name_plural': 'Catagories'},
        ),
        migrations.AlterField(
            model_name='catagory',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
